# Generated by Django 5.1b1 on 2025-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_full_subscription_order_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
