# Generated by Django 5.1b1 on 2025-04-19 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_bid_programmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('order', 'programmer')},
        ),
    ]
