# Generated by Django 5.1b1 on 2025-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_bid_options_order_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
