# Generated by Django 5.1b1 on 2025-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
