# Generated by Django 5.1b1 on 2025-04-09 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmer', '0002_alter_portfolio_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('web', 'Веб-разработка'), ('bots', 'Разработка ботов'), ('logos', 'Дизайн логотипов'), ('mobile', 'Мобильная разработка'), ('game', 'Разработка игр'), ('data_science', 'Data Science и машинное обучение'), ('ai', 'Искусственный интеллект'), ('backend', 'Бэкенд-разработка'), ('frontend', 'Фронтенд-разработка'), ('testing', 'Тестирование ПО'), ('other', 'Другое')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
