# Generated by Django 5.1b1 on 2025-04-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmer', '0004_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='username',
        ),
    ]
